bash percent-india.sh
echo "."
echo "."
echo "Q1: percent-india.sh executed successfully!"
echo "."
echo "."
bash gender-india.sh
echo "."
echo "."
echo "Q2: gender-india.sh executed successfully!"
echo "."
echo "."
bash geography-india.sh
echo "."
echo "."
echo "Q3: geography-india.sh executed successfully!"
echo "."
echo "."
bash 3-to-2-ratio.sh
echo "."
echo "."
echo "Q4: 3-to-2-ratio.sh executed successfully!"
echo "."
echo "."
bash 2-to-1-ratio.sh
echo "."
echo "."
echo "Q4: 2-to-1-ratio.sh executed successfully!"
echo "."
echo "."
bash age-india.sh
echo "."
echo "."
echo "Q5: age-india.sh executed successfully!"
echo "."
echo "."
bash literacy-india.sh
echo "."
echo "."
echo "Q6: literacy-india.sh executed successfully!"
echo "."
echo "."
bash region-india.sh
echo "."
echo "."
echo "Q7: region-india.sh executed successfully!"
echo "."
echo "."
bash age-gender.sh
echo "."
echo "."
echo "Q8: age-gender.sh executed successfully!"
echo "."
echo "."
bash literacy-gender.sh
echo "."
echo "."
echo "Q9: literacy-gender.sh executed successfully!"
echo "."
echo "."
echo "All output files are generated!"
